### ISSUE TITLE
error in SDK version

### ISSUE THREAD

**Issue by Mahm0ud-Ahmed** [rutvik110/asset_manager_cli#1]
when add it, show me error in terminal:

The current Dart SDK version is 2.17.6.

Because aagel depends on asset_manager_cli >=0.1.0-dev.0+1 which requires SDK version >=2.18.0 <3.0.0, version solving failed.
Running "flutter pub get" in aagel...                                   
pub get failed (1; Because aagel depends on asset_manager_cli >=0.1.0-dev.0+1 which requires SDK version >=2.18.0 <3.0.0, version solving failed.)

and when modify sdk version: 2.18.0 show me error in terminal:

The current Dart SDK version is 2.17.6.

Because aagel requires SDK version >=2.18.0 <3.0.0, version solving failed.
Running "flutter pub get" in aagel...                                   
pub get failed (1; Because aagel requires SDK version >=2.18.0 <3.0.0, version solving failed.)

**Comment by rutvik110** [comment]
Hey hi! The cli requires dart sdk version >=2.18.0 . The issue can be resolved by updating your dart sdk to version >=2.18.0. 
I'm closing this issue as this needs a dart update on your side.
